import { Users, Target, GitBranch, MessageCircle, PenTool, Palette, Brain } from "lucide-react";

export const AGENTS_CONFIG = {
  "AA-D100": {
    code: "AA-D100",
    name: "Analista de Audiência",
    fullName: "Análise de Audiência e Dream 100",
    description: "Gera micro-personas, lista Dream 100, mapa de dores × desejos",
    color: "from-blue-500 to-blue-600",
    icon: Users,
    greeting: "Olá! Sou o AA-D100, seu Analista de Audiência. 🎯\n\nVou te ajudar a entender profundamente seu público-alvo e mapear os principais influenciadores do seu nicho.\n\nPara começar, me conte:\n1. **Qual é o seu nicho de atuação?**\n2. **Você já tem alguma ideia de quem é seu público ideal?**\n3. **Qual produto/serviço você oferece ou pretende oferecer?**",
    suggestions: [
      "Crie 3 micro-personas para o meu nicho",
      "Monte minha lista Dream 100",
      "Mapeie as dores e desejos do meu público",
      "Identifique padrões comportamentais da minha audiência",
    ],
    outputTypes: ["Micro-Personas", "Dream 100", "Mapa Dores×Desejos", "Padrões Comportamentais"],
  },
  "AO-GO": {
    code: "AO-GO",
    name: "Estrategista de Ofertas",
    fullName: "Otimização de Ofertas Grand Slam",
    description: "Cria Escada de Valor, equação de valor, variações de copy e pricing",
    color: "from-amber-500 to-amber-600",
    icon: Target,
    greeting: "Olá! Sou o AO-GO, seu Estrategista de Ofertas Grand Slam. 💰\n\nVou criar ofertas irresistíveis usando o framework de Alex Hormozi.\n\nPara começar, preciso saber:\n1. **Qual é o seu produto/serviço principal?**\n2. **Qual é o preço atual (ou pretendido)?**\n3. **Qual transformação seu produto entrega?**",
    suggestions: [
      "Crie minha Escada de Valor com 5 degraus",
      "Calcule a equação de valor da minha oferta",
      "Gere 3 variações de copy para meu produto",
      "Defina a estratégia de pricing",
    ],
    outputTypes: ["Escada de Valor", "Equação de Valor", "Stack de Oferta", "Variações de Copy", "Pricing Strategy"],
  },
  "AJ-AF": {
    code: "AJ-AF",
    name: "Arquiteto de Funil",
    fullName: "Jornada e Automação de Funil",
    description: "Mapeia jornada do lead, gatilhos, sequências de email, lead scoring",
    color: "from-green-500 to-green-600",
    icon: GitBranch,
    greeting: "Olá! Sou o AJ-AF, seu Arquiteto de Funil. 🔄\n\nVou desenhar seu funil de vendas completo com automações inteligentes.\n\nPara começar:\n1. **Você já tem um funil ativo? Qual tipo?**\n2. **Qual é seu principal canal de aquisição?**\n3. **Qual ferramenta de email/automação você usa?**",
    suggestions: [
      "Mapeie a jornada completa do meu lead",
      "Crie uma sequência de email nurturing",
      "Configure meu lead scoring",
      "Desenhe meu funil de vendas completo",
    ],
    outputTypes: ["Mapa do Funil", "Sequência de Email", "Lead Scoring", "Gatilhos de Automação", "KPIs"],
  },
  "AE-C": {
    code: "AE-C",
    name: "Especialista em Engajamento",
    fullName: "Engajamento Conversacional",
    description: "Scripts de Epiphany Bridge, fluxos de conversa, qualificação BANT",
    color: "from-pink-500 to-pink-600",
    icon: MessageCircle,
    greeting: "Olá! Sou o AE-C, seu Especialista em Engajamento. 💬\n\nVou criar scripts de alta conversão e fluxos de conversa que vendem.\n\nPara começar:\n1. **Qual é seu principal canal de vendas? (DM, WhatsApp, Live, Webinário)**\n2. **Qual é a principal objeção que seus prospects têm?**\n3. **Você tem uma história de transformação para compartilhar?**",
    suggestions: [
      "Crie um script de Epiphany Bridge",
      "Desenvolva um fluxo de conversa para vendas",
      "Monte a qualificação BANT do meu cliente",
      "Gere scripts para minha próxima live",
    ],
    outputTypes: ["Epiphany Bridge", "Fluxo de Conversa", "Qualificação BANT", "Script de Live", "Handling de Objeções"],
  },
  "AM-CC": {
    code: "AM-CC",
    name: "Copywriter Estratégico",
    fullName: "Marketing e Conteúdo Criativo",
    description: "Páginas de vendas, sequências de email, hooks, scripts de vídeo",
    color: "from-purple-500 to-purple-600",
    icon: PenTool,
    greeting: "Olá! Sou o AM-CC, seu Copywriter Estratégico. ✍️\n\nVou criar copy de alta conversão para todos os seus canais.\n\nPara começar:\n1. **Qual peça de copy você precisa agora?** (página de vendas, emails, hooks, VSL)\n2. **Qual é o tom da sua marca?** (profissional, casual, provocativo, inspiracional)\n3. **Qual ação você quer que o leitor tome?**",
    suggestions: [
      "Crie uma página de vendas completa",
      "Gere 10 hooks virais para Instagram",
      "Escreva um script de VSL",
      "Crie uma sequência de email de lançamento",
    ],
    outputTypes: ["Página de Vendas", "Sequência de Email", "Hooks Virais", "Script de VSL", "Headlines e CTAs"],
  },
  "AC-DC": {
    code: "AC-DC",
    name: "Designer de Conversão",
    fullName: "Design e Criativos",
    description: "Briefings visuais, prompts de IA, specs por plataforma, paleta de cores",
    color: "from-orange-500 to-orange-600",
    icon: Palette,
    greeting: "Olá! Sou o AC-DC, seu Designer de Conversão. 🎨\n\nVou criar briefings visuais e diretrizes de design que convertem.\n\nPara começar:\n1. **Você já tem identidade visual definida?**\n2. **Quais plataformas são prioridade?** (Instagram, YouTube, TikTok, Site)\n3. **Tem alguma referência visual que admira?**",
    suggestions: [
      "Crie um briefing visual para minha marca",
      "Gere prompts de imagem para meus criativos",
      "Defina specs de design por plataforma",
      "Sugira uma paleta de cores para meu nicho",
    ],
    outputTypes: ["Briefing Visual", "Prompts de IA", "Specs por Plataforma", "Paleta de Cores", "Guidelines de Marca"],
  },
  "ACO": {
    code: "ACO",
    name: "Orquestrador Central",
    fullName: "Orquestrador Central",
    description: "Diagnóstico de coerência, gaps, plano de ação priorizado",
    color: "from-indigo-500 to-indigo-600",
    icon: Brain,
    greeting: "Olá! Sou o ACO, seu Orquestrador Central. 🧠\n\nMinha missão é analisar todos os outputs dos outros agentes e garantir que sua estratégia seja coerente.\n\nVou verificar os outputs aprovados dos outros agentes e te dar um diagnóstico completo.\n\n**O que você gostaria que eu analisasse primeiro?**",
    suggestions: [
      "Faça um diagnóstico completo da minha estratégia",
      "Identifique gaps na minha estrutura",
      "Crie um plano de ação priorizado",
      "Qual a ordem ideal para usar os agentes?",
    ],
    outputTypes: ["Diagnóstico de Coerência", "Gaps Identificados", "Plano de Ação", "Matriz de Dependências", "Score de Maturidade"],
  },
} as const;

export type AgentCode = keyof typeof AGENTS_CONFIG;
