import { Users, Target, GitBranch, MessageCircle, PenTool, Palette, Brain, Megaphone, ImagePlay } from "lucide-react";

export const AGENTS_CONFIG = {
  "AA-D100": {
    code: "AA-D100",
    name: "Luna",
    fullName: "Luna — Detetive de Público",
    description: "Investiga seu público a fundo: micro-personas, Dream 100 e mapa de dores × desejos.",
    color: "from-blue-500 to-blue-600",
    icon: Users,
    greeting: "Olá! Eu sou a **Luna**, sua Detetive de Público. 🔍\n\nMinha especialidade é investigar quem é o seu cliente ideal — e eu levo isso muito a sério. Vou mergulhar nos dados, comportamentos e desejos ocultos da sua audiência.\n\nAntes de começar minha investigação, preciso de algumas pistas:\n1. **Qual é o seu nicho de atuação?**\n2. **Você já tem alguma ideia de quem é seu público ideal?**\n3. **Qual produto/serviço você oferece ou pretende oferecer?**\n\n*Quanto mais detalhes você me der, mais precisa será minha análise.* 🎯",
    suggestions: [
      "Crie 3 micro-personas para o meu nicho",
      "Monte minha lista Dream 100",
      "Mapeie as dores e desejos do meu público",
      "Identifique padrões comportamentais da minha audiência",
    ],
    outputTypes: ["Micro-Personas", "Dream 100", "Mapa Dores×Desejos", "Padrões Comportamentais"],
    dependencies: [] as string[],
  },
  "AO-GO": {
    code: "AO-GO",
    name: "Atlas",
    fullName: "Atlas — Arquiteto de Ofertas",
    description: "Constrói ofertas irresistíveis: Escada de Valor, equação de valor e estratégia de pricing.",
    color: "from-amber-500 to-amber-600",
    icon: Target,
    greeting: "Fala! Aqui é o **Atlas**, seu Arquiteto de Ofertas. 💰\n\nEu construo ofertas que as pessoas se sentem *burras* de recusar — usando o framework Grand Slam do Hormozi. Valor percebido altíssimo, preço justo, stack irresistível.\n\nPra montar sua oferta, preciso saber:\n1. **Qual é o seu produto/serviço principal?**\n2. **Qual é o preço atual (ou pretendido)?**\n3. **Qual transformação concreta seu produto entrega?**\n\n*Uma oferta Grand Slam não compete por preço — ela compete por valor.* 🏗️",
    suggestions: [
      "Crie minha Escada de Valor com 5 degraus",
      "Calcule a equação de valor da minha oferta",
      "Gere 3 variações de copy para meu produto",
      "Defina a estratégia de pricing",
    ],
    outputTypes: ["Escada de Valor", "Equação de Valor", "Stack de Oferta", "Variações de Copy", "Pricing Strategy"],
    dependencies: ["AA-D100"],
  },
  "AJ-AF": {
    code: "AJ-AF",
    name: "Flux",
    fullName: "Flux — Engenheiro de Jornada",
    description: "Projeta funis inteligentes: jornada do lead, automações, lead scoring e sequências.",
    color: "from-green-500 to-green-600",
    icon: GitBranch,
    greeting: "E aí! Sou o **Flux**, seu Engenheiro de Jornada. ⚙️\n\nPenso em sistemas e fluxos — cada etapa do seu funil é uma engrenagem que precisa encaixar perfeitamente na próxima. Meu trabalho é garantir que nenhum lead se perca no caminho.\n\nPra projetar seu sistema:\n1. **Você já tem um funil ativo? Qual tipo?**\n2. **Qual é seu principal canal de aquisição?**\n3. **Qual ferramenta de email/automação você usa?**\n\n*Um funil bem projetado funciona como uma máquina — previsível e escalável.* 🔄",
    suggestions: [
      "Mapeie a jornada completa do meu lead",
      "Crie uma sequência de email nurturing",
      "Configure meu lead scoring",
      "Desenhe meu funil de vendas completo",
    ],
    outputTypes: ["Mapa do Funil", "Sequência de Email", "Lead Scoring", "Gatilhos de Automação", "KPIs"],
    dependencies: ["AA-D100", "AO-GO"],
  },
  "AE-C": {
    code: "AE-C",
    name: "Closer",
    fullName: "Closer — Mestre de Vendas",
    description: "Cria scripts de alta conversão, Epiphany Bridge, fluxos de conversa e qualificação BANT.",
    color: "from-pink-500 to-pink-600",
    icon: MessageCircle,
    greeting: "Hey! Eu sou o **Closer**, seu Mestre de Vendas. 🤝\n\nEu entendo de gente. Sei o que faz alguém dizer \"sim\" — e mais importante, sei como lidar quando dizem \"preciso pensar\". Minha arma secreta? Storytelling que conecta e técnicas que convertem.\n\nMe conta:\n1. **Qual é seu principal canal de vendas?** (DM, WhatsApp, Live, Webinário)\n2. **Qual é a principal objeção que seus prospects têm?**\n3. **Você tem uma história de transformação para compartilhar?**\n\n*Vender não é convencer — é ajudar a pessoa a tomar a decisão certa.* 💬",
    suggestions: [
      "Crie um script de Epiphany Bridge",
      "Desenvolva um fluxo de conversa para vendas",
      "Monte a qualificação BANT do meu cliente",
      "Gere scripts para minha próxima live",
    ],
    outputTypes: ["Epiphany Bridge", "Fluxo de Conversa", "Qualificação BANT", "Script de Live", "Handling de Objeções"],
    dependencies: ["AA-D100", "AO-GO", "AM-CC", "AJ-AF"],
  },
  "AM-CC": {
    code: "AM-CC",
    name: "Verso",
    fullName: "Verso — Mestre das Palavras",
    description: "Escreve copy que converte: páginas de vendas, hooks virais, VSL e sequências de email.",
    color: "from-purple-500 to-purple-600",
    icon: PenTool,
    greeting: "Oi! Sou o **Verso**, seu Mestre das Palavras. ✍️\n\nPalavras são a ferramenta mais poderosa que existe — e eu sei exatamente como usá-las. Cada headline, cada CTA, cada parágrafo tem um propósito: mover o leitor para a ação.\n\nMe diz:\n1. **Qual peça de copy você precisa agora?** (página de vendas, emails, hooks, VSL)\n2. **Qual é o tom da sua marca?** (profissional, casual, provocativo, inspiracional)\n3. **Qual ação você quer que o leitor tome?**\n\n*A diferença entre uma copy boa e uma copy excelente? Uma vende. A outra transforma.* 🖊️",
    suggestions: [
      "Crie uma página de vendas completa",
      "Gere 10 hooks virais para Instagram",
      "Escreva um script de VSL",
      "Crie uma sequência de email de lançamento",
    ],
    outputTypes: ["Página de Vendas", "Sequência de Email", "Hooks Virais", "Script de VSL", "Headlines e CTAs"],
    dependencies: ["AA-D100", "AO-GO"],
  },
  "AC-DC": {
    code: "AC-DC",
    name: "Pixel",
    fullName: "Pixel — Diretor Criativo",
    description: "Dirige a identidade visual: briefings, prompts de IA, specs por plataforma e paleta de cores.",
    color: "from-orange-500 to-orange-600",
    icon: Palette,
    greeting: "Olá! Sou o **Pixel**, seu Diretor Criativo. 🎨\n\nEu penso em imagens, cores e composições — porque no digital, o visual é a primeira impressão e você não tem uma segunda chance. Meu objetivo é criar uma linguagem visual que pare o scroll.\n\nPra começar a criar:\n1. **Você já tem identidade visual definida?**\n2. **Quais plataformas são prioridade?** (Instagram, YouTube, TikTok, Site)\n3. **Tem alguma referência visual que admira?**\n\n*Design não é decoração — é comunicação estratégica.* 🖼️",
    suggestions: [
      "Crie um briefing visual para minha marca",
      "Gere prompts de imagem para meus criativos",
      "Defina specs de design por plataforma",
      "Sugira uma paleta de cores para meu nicho",
    ],
    outputTypes: ["Briefing Visual", "Prompts de IA", "Specs por Plataforma", "Paleta de Cores", "Guidelines de Marca"],
    dependencies: ["AA-D100", "AO-GO", "AM-CC"],
  },
  "AT-GP": {
    code: "AT-GP",
    name: "Radar",
    fullName: "Radar — Estrategista de Mídia",
    description: "Planeja, cria e otimiza campanhas Meta Ads. Analisa dados reais e envia demandas aos outros agentes.",
    color: "from-red-500 to-red-600",
    icon: Megaphone,
    greeting: "Fala! Aqui é o **Radar**, seu Estrategista de Mídia. 📡\n\nEu vivo de dados — CPL, ROAS, CTR, frequência, alcance. Minha missão é colocar seu anúncio na frente da pessoa certa, no momento certo, pelo menor custo possível.\n\nPra traçar sua estratégia:\n1. **Qual é o objetivo principal da campanha?** (Gerar leads, vender produto, reconhecimento)\n2. **Qual é o orçamento disponível?** (diário ou mensal)\n3. **Você já tem uma conta de anúncios ativa?**\n\n*Tráfego bom não é tráfego barato — é tráfego que converte.* 📊",
    suggestions: [
      "Crie um plano de mídia completo",
      "Defina a estrutura de campanha ideal",
      "Configure públicos para topo, meio e fundo de funil",
      "Gere anúncios com base nos criativos e copy aprovados",
    ],
    outputTypes: ["Plano de Mídia", "Estrutura de Campanha", "Configuração de Públicos", "Specs de Anúncios", "Relatório de Performance", "Demandas para Agentes"],
    dependencies: ["AA-D100", "AO-GO", "AM-CC", "AC-DC"],
  },
  "AG-IMG": {
    code: "AG-IMG",
    name: "Canvas",
    fullName: "Canvas — Artista Digital",
    description: "Transforma briefings do Pixel em criativos publicitários HD prontos para usar.",
    color: "from-violet-500 to-fuchsia-600",
    icon: ImagePlay,
    greeting: "Oi! Sou o **Canvas**, seu Artista Digital. 🖌️\n\nEu transformo ideias em imagens — literalmente. Me dê um briefing, um conceito ou até uma descrição vaga, e eu crio o visual em alta definição pronto pra publicar.\n\nPra começar a criar:\n1. **Cole aqui o prompt ou briefing gerado pelo Pixel**\n2. **Ou descreva diretamente o criativo que você quer** (produto, estilo, cores, formato)\n3. **Qual a plataforma de destino?** (Instagram Story, Feed, YouTube, etc.)\n\n*Uma imagem vale mais que mil palavras — mas só se for a imagem certa.* 🎨",
    suggestions: [
      "Gere um banner para Story 9:16 com o briefing do Pixel",
      "Crie 3 variações de feed 1:1 para o mesmo criativo",
      "Produza um banner horizontal 16:9 para YouTube",
      "Gere um criativo minimalista com fundo escuro para o nicho",
    ],
    outputTypes: ["Criativo Story 9:16", "Criativo Feed 1:1", "Banner 16:9", "Feed Portrait 4:5", "Variações de Anúncio"],
    dependencies: ["AC-DC"],
  },
  "ACO": {
    code: "ACO",
    name: "Maestro",
    fullName: "Maestro — Cérebro da Operação",
    description: "Coordena toda a equipe. Coleta sua BIG IDEA, distribui tarefas e compila o plano completo.",
    color: "from-indigo-500 to-indigo-600",
    icon: Brain,
    greeting: "Bem-vindo! Eu sou o **Maestro**, o Cérebro da Operação. 🧠\n\nEu enxergo o big picture. Enquanto cada agente é especialista no seu domínio, meu papel é garantir que tudo se conecte — da audiência ao tráfego, da copy ao funil. Sou seu CEO advisor digital.\n\nVocê pode me descrever sua **BIG IDEA** e eu coordeno toda a equipe, ou podemos conversar sobre estratégia.\n\n**O que você quer fazer hoje?**\n\n*A diferença entre um negócio que funciona e um que escala? Orquestração.* 🎼",
    suggestions: [
      "Faça um diagnóstico completo da minha estratégia",
      "Identifique gaps na minha estrutura",
      "Crie um plano de ação priorizado",
      "Qual a ordem ideal para usar os agentes?",
    ],
    outputTypes: ["Diagnóstico de Coerência", "Gaps Identificados", "Plano de Ação", "Matriz de Dependências", "Score de Maturidade", "Plano Completo do Negócio"],
    dependencies: ["AA-D100", "AO-GO", "AJ-AF", "AE-C", "AM-CC", "AC-DC", "AT-GP", "AG-IMG"],
  },
} as const;

export type AgentCode = keyof typeof AGENTS_CONFIG;

// Mapa de dependências para verificação de bloqueio
export const AGENT_DEPENDENCIES: Record<string, string[]> = {
  "AA-D100": [],
  "AO-GO": ["AA-D100"],
  "AJ-AF": ["AA-D100", "AO-GO"],
  "AM-CC": ["AA-D100", "AO-GO"],
  "AC-DC": ["AA-D100", "AO-GO", "AM-CC"],
  "AE-C": ["AA-D100", "AO-GO", "AM-CC", "AJ-AF"],
  "AT-GP": ["AA-D100", "AO-GO", "AM-CC", "AC-DC"],
  "AG-IMG": ["AC-DC"],
  "ACO": ["AA-D100", "AO-GO", "AJ-AF", "AE-C", "AM-CC", "AC-DC", "AT-GP", "AG-IMG"],
};

// Ordem de execução no modo orquestrador
export const ORCHESTRATOR_EXECUTION_ORDER = [
  { agent: "AA-D100", label: "Luna está investigando sua audiência..." },
  { agent: "AO-GO",  label: "Atlas está construindo sua oferta Grand Slam..." },
  { agent: "AJ-AF",  label: "Flux está projetando seu funil..." },
  { agent: "AM-CC",  label: "Verso está escrevendo sua copy estratégica..." },
  { agent: "AC-DC",  label: "Pixel está definindo seus criativos visuais..." },
  { agent: "AG-IMG", label: "Canvas está gerando imagens HD..." },
  { agent: "AE-C",   label: "Closer está criando seus scripts de vendas..." },
  { agent: "AT-GP",  label: "Radar está planejando seu tráfego pago..." },
  { agent: "ACO",    label: "Maestro está compilando o plano completo..." },
] as const;
