
INSERT INTO public.knowledge_base (agent_code, title, content, category, is_active)
VALUES

-- ============================================================
-- AA-D100: Análise de Audiência + Dream 100
-- ============================================================
(
  'AA-D100',
  'Metodologia Dream 100',
  E'Dream 100 é a estratégia criada por Chet Holmes e popularizada por Russell Brunson para identificar os 100 influenciadores, comunidades e plataformas onde sua audiência ideal já está congregada.\n\nCONCEITO CENTRAL\nEm vez de tentar encontrar novos clientes do zero, o Dream 100 mapeia onde eles já estão — quais canais assistem, quais podcasts ouvem, quais grupos participam, quais influenciadores seguem — e entra nessas conversas já existentes.\n\nPASSO 1: IDENTIFICAR A AUDIÊNCIA IDEAL\n- Definir o avatar (ICP): cargo, setor, dores, objetivos, faixa de faturamento\n- Mapear comportamentos digitais: onde pesquisa, consome conteúdo, toma decisões de compra\n- Listar características psicográficas: valores, crenças, aspirações\n\nPASSO 2: CONSTRUIR A LISTA DREAM 100\nCategorie os 100 alvos em:\n- Influenciadores e criadores de conteúdo do nicho\n- Podcasts e canais do YouTube da audiência\n- Grupos e comunidades (Facebook, Discord, WhatsApp, Skool)\n- Newsletters e blogs relevantes\n- Eventos presenciais e virtuais (feiras, congressos, mastermind)\n- Perfis no Instagram, LinkedIn, TikTok\n\nPASSO 3: DIG THE WELL (Cavando o Poço)\nAntes de pedir qualquer coisa, construa relacionamento:\n- Comentar e engajar com consistência por 30-60 dias\n- Compartilhar o conteúdo deles genuinamente\n- Enviar mensagem de valor real sem pitch\n\nPASSO 4: BUY YOUR WAY IN (Comprar a Entrada)\n- Anúncios direcionados para seguidores dos Dream 100\n- Patrocínio de newsletters e podcasts\n- Retargeting da audiência dos alvos\n\nPASSO 5: WORK YOUR WAY IN (Conquistar a Entrada)\n- Proposta de parceria / co-criação de conteúdo\n- Convite para webinário ou live\n- Collab, troca de audiências, guest post\n\nMÉTRICAS PARA ACOMPANHAR\n- Taxa de resposta a abordagens (benchmark: >15%)\n- CPL de audiências de parceiros vs. cold traffic\n- Conversão de audiências aquecidas vs. frias\n- Nº de parceiros ativos por mês\n\nRESULTADO ESPERADO: Acesso à audiência já qualificada e aquecida, redução do CAC e aumento da velocidade de confiança.',
  'metodologia',
  true
),
(
  'AA-D100',
  'Análise de Audiência: Avatar e ICP',
  E'Para construir o Dream 100 é essencial ter clareza absoluta sobre quem é a audiência ideal. Use este framework de análise de avatar.\n\nDIMENSÕES DO AVATAR\n\n1. DEMOGRÁFICO\n- Idade, gênero, localização\n- Renda / faturamento da empresa\n- Cargo e setor\n- Nível de escolaridade\n\n2. PSICOGRÁFICO (mais importante)\n- Maiores medos e frustrações\n- Maiores desejos e aspirações\n- Crenças sobre si mesmo e sobre o mercado\n- O que o mantém acordado à noite\n- Como mede sucesso\n\n3. COMPORTAMENTAL\n- Onde busca informação (Google, YouTube, redes sociais)\n- Quais influenciadores consome\n- Frequência e formato de conteúdo preferido\n- Como toma decisões de compra (rápido/lento, sozinho/com sócio)\n- Objeções mais comuns\n\n4. MAPA DE DOR (Pain Stack)\nListe as dores em ordem de intensidade:\n- Dor nível 1 (irritação): pequenos incômodos do dia a dia\n- Dor nível 2 (problema): algo que atrapalha recorrentemente\n- Dor nível 3 (crise): algo que ameaça o negócio ou sonho\n\nQUESTIONÁRIO PARA ENTREVISTAS DE AVATAR\n1. Qual é o maior desafio que você enfrenta hoje em [área]?\n2. O que você já tentou para resolver isso? Por que não funcionou?\n3. Se você pudesse resolver esse problema amanhã, o que mudaria?\n4. Quanto esse problema está custando para você (tempo, dinheiro, energia)?\n5. O que te impediria de investir em uma solução agora?\n\nBENCHMARK: realize pelo menos 10 entrevistas qualitativas antes de criar qualquer campanha.',
  'analise-audiencia',
  true
),

-- ============================================================
-- AO-GO: Grand Slam Offer (Hormozi) + Escada de Valor
-- ============================================================
(
  'AO-GO',
  'Framework Grand Slam Offer (Alex Hormozi)',
  E'Grand Slam Offer é o conceito central do livro "$100M Offers" de Alex Hormozi. O objetivo é criar uma oferta tão irresistível que o cliente se sinta idiota em dizer não.\n\nPRINCÍPIO FUNDAMENTAL\n"Não venda o produto, venda o resultado. E empilhe tanto valor percebido que o preço pareça ridículo perto do que está sendo oferecido."\n\nFÓRMULA DA OFERTA GRAND SLAM\nValor = (Sonho × Probabilidade de alcançar) / (Tempo até resultado × Esforço e sacrifício)\n\nPara maximizar o valor percebido:\n- ↑ Aumentar o tamanho do sonho (outcome desejado)\n- ↑ Aumentar a probabilidade percebida de sucesso\n- ↓ Diminuir o tempo até ver o resultado\n- ↓ Diminuir o esforço e sacrifício exigidos\n\nPASS 1: IDENTIFICAR O RESULTADO CENTRAL (Dream Outcome)\nQual é a transformação final que o cliente quer? Seja específico:\n- Ruim: "Aprenda marketing digital"\n- Bom: "Consiga seus primeiros 10 clientes em 90 dias sem gastar R$1 em anúncios"\n\nPASSO 2: LISTAR TODOS OS PROBLEMAS (Problem Stack)\nMapeie cada obstáculo que o cliente enfrenta para atingir o resultado:\n- Problemas de conhecimento (não sei como fazer)\n- Problemas de tempo (não tenho tempo)\n- Problemas de crença (acho que não funciona pra mim)\n- Problemas de implementação (sei mas não consigo executar)\n\nPASSO 3: CRIAR SOLUÇÕES PARA CADA PROBLEMA (Value Stack)\nPara cada problema, crie um entregável, bônus ou mecanismo:\n- Problema: "Não sei como prospectar" → Solução: Script de prospecção validado + 30 dias de mentoria\n- Problema: "Não tenho tempo" → Solução: Templates prontos + implementação feita para você\n- Problema: "E se não funcionar?" → Solução: Garantia de resultado ou dinheiro de volta\n\nPASSO 4: EMPILHAR OS ENTREGÁVEIS (Stack the Deliverables)\nApresente cada item com nome, valor unitário e benefício.\nExemplo de Stack:\n✓ Módulo principal — R$3.000\n✓ Script de prospecção — R$500\n✓ Planilha de pipeline — R$300\n✓ 4 sessões de mentoria — R$2.000\n✓ Acesso à comunidade — R$800\n✓ Garantia de 90 dias — sem risco\nTotal de valor: R$6.600 → Preço: R$1.997\n\nPASSO 5: CRIAR URGÊNCIA E ESCASSEZ REAIS\n- Vagas limitadas (e realmente limitar)\n- Bônus por tempo determinado\n- Aumento de preço programado\n- Cohorte com início fixo\n\nPASSO 6: NOMEAR A OFERTA\nUse a fórmula: [Resultado específico] + [Prazo] + [Sem/Mesmo que objeção principal]\nExemplo: "Programa 10 Clientes em 90 Dias — Mesmo Que Você Nunca Tenha Vendido Online"\n\nGARANTIAS QUE DESTROEM OBJEÇÕES\n- Garantia incondicional: "30 dias de satisfação ou devolvemos 100%"\n- Garantia de resultado: "Se não conseguir X em Y dias, trabalhamos de graça até conseguir"\n- Garantia reversa: "Se não gostar, pode ficar com os bônus"',
  'framework',
  true
),
(
  'AO-GO',
  'Escada de Valor (Value Ladder)',
  E'A Escada de Valor é o modelo estratégico de ascensão de clientes, onde cada produto/serviço prepara o cliente para o próximo nível de investimento.\n\nCONCEITO\nEm vez de tentar vender o produto mais caro logo de início, você constrói uma jornada de confiança progressiva. Cada degrau entrega valor real e cria desejo pelo próximo nível.\n\nESTRUTURA DA ESCADA\n\nDEGRAU 1 — ISCA (Lead Magnet)\n- Preço: gratuito ou R$1-50\n- Objetivo: capturar leads e entregar vitória rápida\n- Exemplos: ebook, checklist, mini-curso, webinário, ferramenta gratuita\n- KPI: taxa de conversão de visitante → lead (benchmark: >20%)\n\nDEGRAU 2 — TRIPWIRE / FRONT-END\n- Preço: R$47-297\n- Objetivo: transformar lead em comprador (quebrar a barreira psicológica do primeiro pagamento)\n- Exemplos: curso introdutório, workshop gravado, sessão de diagnóstico\n- KPI: conversão de lead → comprador (benchmark: 2-5%)\n\nDEGRAU 3 — PRODUTO CORE (Mid-Ticket)\n- Preço: R$500-3.000\n- Objetivo: entrega da transformação principal\n- Exemplos: curso completo, mentoria em grupo, programa de aceleração\n- KPI: LTV por cohorte, taxa de conclusão\n\nDEGRAU 4 — HIGH-TICKET\n- Preço: R$5.000-30.000+\n- Objetivo: resultado premium com atenção individualizada\n- Exemplos: mentoria 1:1, consultoria, mastermind, feito para você\n- KPI: taxa de renovação, NPS, resultados dos clientes\n\nDEGRAU 5 — CONTINUIDADE (Recorrência)\n- Preço: R$97-997/mês\n- Objetivo: receita previsível e retenção de longo prazo\n- Exemplos: comunidade, software, assinatura, grupo de mastermind mensal\n- KPI: MRR, churn rate (benchmark saudável: <5%/mês)\n\nSTRATÉGIA DE ASCENSÃO\n1. Entregue resultado no degrau atual antes de oferecer o próximo\n2. Use a oferta de continuidade como "próximo passo natural"\n3. Crie ofertas de Order Bump e Upsell entre os degraus\n4. Meça o LTV por degrau para saber onde focar aquisição',
  'estrategia',
  true
),

-- ============================================================
-- AJ-AF: Jornada do Lead, Lead Scoring e Funil de Automação
-- ============================================================
(
  'AJ-AF',
  'Lead Scoring: Qualificação e Priorização de Leads',
  E'Lead Scoring é o sistema de pontuação que classifica leads por probabilidade de conversão, permitindo priorizar os esforços de venda e automação.\n\nPOR QUE USAR LEAD SCORING\n- 79% dos leads nunca se convertem por falta de nutrição adequada (Marketing Sherpa)\n- Times de vendas desperdiçam 50% do tempo em leads não qualificados\n- Empresas com lead scoring têm 77% maior ROI em geração de leads\n\nMODELO DE LEAD SCORING: BANT + COMPORTAMENTAL\n\nCRITÉRIOS DEMOGRÁFICOS / FIRMOGRÁFICOS (0-40 pontos)\n+10 pts: Cargo decisor (CEO, CMO, Fundador, Diretor)\n+10 pts: Faturamento no range ideal do ICP\n+10 pts: Setor/nicho alvo\n+5 pts: Empresa com time de marketing\n+5 pts: Tamanho de empresa ideal\n-10 pts: Cargo júnior sem poder de decisão\n-10 pts: Setor fora do ICP\n\nCRITÉRIOS COMPORTAMENTAIS (0-60 pontos)\n+15 pts: Solicitou demonstração ou proposta\n+10 pts: Visitou página de preços 2+ vezes\n+10 pts: Abriu 3+ emails da sequência\n+8 pts: Assistiu webinário por mais de 50% do tempo\n+7 pts: Baixou material rico (ebook, template)\n+5 pts: Visitou o site 3+ vezes na última semana\n+5 pts: Clicou em CTA de vendas\n+5 pts: Respondeu a email de nutrição\n-5 pts: Inativo por 30+ dias\n-10 pts: Visitou apenas página "Careers" (provável concorrente)\n\nCLASSIFICAÇÃO POR SCORE\n- 0-30 pts: FRIO → nutrição automática longa (60-90 dias)\n- 31-60 pts: MORNO → nutrição acelerada + retargeting\n- 61-80 pts: QUENTE → SDR entre em contato em 24h\n- 81-100 pts: MUITO QUENTE → alerta imediato para vendas, contato em 2h\n\nIMPLEMENTAÇÃO TÉCNICA\n- Integrar scoring com CRM (HubSpot, RD Station, ActiveCampaign)\n- Criar alertas automáticos para score alto\n- Revisar e calibrar scoring a cada 90 dias com dados reais de conversão\n- A/B testar thresholds de passagem para SDR',
  'lead-scoring',
  true
),
(
  'AJ-AF',
  'Funil de Automação: Sequências e Jornada do Lead',
  E'Funil de automação é o conjunto de sequências e triggers que nutrem o lead de forma personalizada ao longo da jornada de compra, do primeiro contato até a conversão.\n\nFASES DA JORNADA DO LEAD\n\nFASE 1: TOPO — ATRAÇÃO E CAPTURA\nObjetivo: Gerar lead qualificado\nCanais: SEO, tráfego pago, redes sociais, parceiros\nTriggers: Preenchimento de formulário, download de isca digital\n\nSequência de Boas-vindas (3 emails em 5 dias):\n- Email 1 (imediato): Entrega da isca + expectativa da próxima comunicação\n- Email 2 (dia 2): Conteúdo de valor relacionado à dor principal\n- Email 3 (dia 5): Apresentação da empresa + prova social + CTA suave\n\nFASE 2: MEIO — NUTRIÇÃO E QUALIFICAÇÃO\nObjetivo: Educar, construir autoridade e elevar score\nDuração: 21-45 dias\nCadência: 2-3 emails/semana\n\nSequência de Nutrição (exemplo 21 dias):\n- Semana 1: Educação sobre o problema (conteúdo, dados, pesquisas)\n- Semana 2: Apresentação de soluções possíveis (posicionamento)\n- Semana 3: Diferenciação + prova social + oferta de diagnóstico\n\nSEGMENTAÇÃO POR COMPORTAMENTO\n- Abriu mas não clicou → reenvio com assunto diferente em 3 dias\n- Clicou mas não converteu → sequência de objeções específicas\n- Assistiu webinário → sequência de follow-up com replay + oferta\n- Inativo 14 dias → sequência de reengajamento ("Você ainda quer resolver X?")\n\nFASE 3: FUNDO — CONVERSÃO\nObjetivo: Converter lead aquecido em cliente\nTrigger: Lead score ≥ 61 pts ou ação de intenção clara\n\nSequência de Conversão (5 emails em 7 dias):\n- Email 1: Apresentação da oferta com foco no resultado\n- Email 2: Prova social + case de sucesso específico\n- Email 3: FAQ + destruição de objeções\n- Email 4: Urgência real (prazo, vagas, preço)\n- Email 5: Último aviso + bônus por decisão\n\nFASE 4: PÓS-VENDA — ONBOARDING E EXPANSÃO\nObjetivo: Garantir resultado do cliente + upsell\n\nSequência de Onboarding (primeiros 30 dias):\n- Dia 1: Boas-vindas + próximos passos claros\n- Dia 3: Check-in de ativação ("Você já completou o passo 1?")\n- Dia 7: Primeiro marco + celebração + próximo objetivo\n- Dia 14: Pesquisa de satisfação + identificação de oportunidade de upsell\n- Dia 30: Review de resultados + oferta do próximo nível\n\nMÉTRICAS-CHAVE DO FUNIL\n- Taxa de abertura de email (benchmark: >25%)\n- Taxa de clique (CTR benchmark: >3%)\n- Tempo médio de conversão (lead → cliente)\n- Taxa de conversão por fase do funil\n- Churn nos primeiros 30 dias pós-compra',
  'automacao',
  true
),
(
  'AJ-AF',
  'Automação: Triggers e Fluxos por Comportamento',
  E'Triggers comportamentais são ações do lead que disparam sequências automatizadas personalizadas, aumentando relevância e conversão.\n\nPRINCIPAIS TRIGGERS E FLUXOS\n\nTRIGGER: VISITA À PÁGINA DE PREÇOS\n- Condição: visitou /precos 2+ vezes em 7 dias\n- Score: +10 pts\n- Ação: Alerta para SDR + email automático de "posso ajudar?" em 2h\n- Mensagem modelo: "Vi que você passou pelo nosso plano. Tem alguma dúvida que posso responder rapidamente?"\n\nTRIGGER: ABANDONO DE CHECKOUT\n- Condição: iniciou pagamento mas não concluiu\n- Sequência de recuperação (3 mensagens em 48h):\n  1. 1h depois: "Algo aconteceu? Seu pedido está reservado."\n  2. 6h depois: FAQ sobre segurança e formas de pagamento\n  3. 24h depois: Oferta de parcelamento ou bônus adicional por finalizar\n\nTRIGGER: INATIVIDADE\n- Condição: sem abertura de email por 21 dias\n- Sequência de reengajamento:\n  1. Email de "break-up": "Tudo bem? Se não tiver mais interesse, me diga para parar de enviar."\n  2. Se abriu: retornar à sequência de nutrição\n  3. Se não abriu em 7 dias: mover para lista fria, reduzir frequência\n\nTRIGGER: ASSISTIU WEBINÁRIO\n- Condição: participou de live ou assistiu replay por >50%\n- Score: +8 pts\n- Sequência em 5 dias:\n  1. Imediato: Obrigado + link do replay + slide deck\n  2. Dia 2: Principal insight + implementação prática\n  3. Dia 4: Oferta da mentoria/produto com bônus exclusivo para participantes\n  4. Dia 7: Último lembrete com urgência\n\nTRIGGER: NPS BAIXO (DETRATOR)\n- Condição: NPS < 7 após compra\n- Ação imediata: Alerta para CS + email de "me conta o que aconteceu"\n- Objetivo: Resolver antes do churn, transformar detrator em promotor\n\nFERRAMENTAS RECOMENDADAS\n- ActiveCampaign: automação + CRM integrado, ideal para infoprodutos\n- HubSpot: robusto para B2B, pipeline visual\n- RD Station: alternativa nacional com suporte em português\n- Klaviyo: especializado em e-commerce\n- Make (Integromat): integração entre ferramentas sem código',
  'automacao',
  true
);
